name: CI tests

on: [push, pull_request]

jobs:
  linux:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        versions:
          - ghc: '8.0.2'
            cabal: '2.4'
          - ghc: '8.2.2'
            cabal: '2.4'
          - ghc: '8.4.4'
            cabal: '2.4'
          - ghc: '8.6.5'
            cabal: '2.4'
          - ghc: '8.8.1'
            cabal: '3.0'
          - ghc: '8.10.1'
            cabal: '3.2'
    steps:
    - uses: actions/checkout@v1
    - name: Install recent cabal/ghc
      uses: actions/setup-haskell@v1.1
      with:
        ghc-version: ${{ matrix.versions.ghc }}
        cabal-version: ${{ matrix.versions.cabal }}

    - name: Cache cabal global package db
      id:   cabal-global
      uses: actions/cache@v2
      with:
        path: |
          ~/.cabal
        key: ${{ runner.os }}-${{ matrix.versions.ghc }}-${{ matrix.versions.cabal }}-cabal-global-${{ hashFiles('cabal.project') }}

    - name: Cache cabal work
      id:   cabal-local
      uses: actions/cache@v2
      with:
        path: |
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.versions.ghc }}-${{ matrix.versions.cabal }}-cabal-local

    - name: Install dependencies
      run: |
          cabal v2-update
          cabal v2-build --dependencies-only --enable-tests --disable-optimization all
    - name: Build and test
      run: |
          cabal v2-build --enable-tests --disable-optimization all 2>&1 | tee build.log
          # fail if warnings in local build
          # ! grep -q ": *[Ww]arning:" build.log || exit 1
          cabal v2-test --disable-optimization all

  windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install recent cabal/ghc
      uses: actions/setup-haskell@v1.1
      with:
        ghc-version: '8.10.1'
        cabal-version: '3.2'

    - name: Cache cabal global package db
      id:   cabal-global
      uses: actions/cache@v2
      with:
        path: |
          ~/.cabal
        key: ${{ runner.os }}-${{ matrix.versions.ghc }}-${{ matrix.versions.cabal }}-cabal-global-${{ hashFiles('cabal.project') }}

    - name: Cache cabal work
      id:   cabal-local
      uses: actions/cache@v2
      with:
        path: |
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.versions.ghc }}-${{ matrix.versions.cabal }}-cabal-local

    - name: Install dependencies
      run: |
          cabal v2-update
          cabal v2-build --dependencies-only --enable-tests --disable-optimization all
    - name: Build and test
      run: |
          chcp 65001
          cabal v2-test --disable-optimization all

  macos:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install recent cabal/ghc
      uses: actions/setup-haskell@v1.1
      with:
        ghc-version: '8.10.1'
        cabal-version: '3.2'

    - name: Cache cabal global package db
      id:   cabal-global
      uses: actions/cache@v2
      with:
        path: |
          ~/.cabal
        key: ${{ runner.os }}-${{ matrix.versions.ghc }}-${{ matrix.versions.cabal }}-cabal-global-${{ hashFiles('cabal.project') }}

    - name: Cache cabal work
      id:   cabal-local
      uses: actions/cache@v2
      with:
        path: |
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.versions.ghc }}-${{ matrix.versions.cabal }}-cabal-local

    - name: Install dependencies
      run: |
          cabal v2-update
          cabal v2-build --dependencies-only --enable-tests --disable-optimization all
    - name: Build and test
      run: |
          cabal v2-test --disable-optimization all
